simulation_name: Dye-S2b
ts_outbound: 1000
ts_inbound: 1500
step_size: 0.1
seed: [2000, 2099]
noise: [0.0, 0.4]
cx_class: DyeModel
cx_params:
  epsilon: 1.58e+05  # /M/cm
  length: 3.5e-04  # cm
  phi: 0.002  # percentile (0.2%)
  wavelength: 6.53e-07  # m
  k: 9.07e-04  # s^-1
  c_tot: 8.54e-03  # M
  volume: 2.08e-11  # L
  w_max: 1.30e-07  # J/s
  gain: 1.0