simulation_name: AP-048-SC-an
route: random
ts_outbound: 1000
ts_inbound: 1500
step_size: 0.1
seed: [2000, 2099]
noise: 0.1
cx_class: DyeMemoryCX
cx_params:
  epsilon: 1.58e+05  # /M/cm
  length: 2.5e-04  # cm
  phi: 0.002  # percentile (0.2%)
  k: 5.8e-05  # s^-1
  c_tot: 5.72e-03  # M
  wavelength: 6.53e-07  # m
  volume: 3.27e-10  # L
  W_max: 1.30e-07  # J/s
  beta: 0.0
  gain: 0.5